name: 🚀 Deploy to Production
on:
  workflow_run:
    workflows: ["🚀 Deploy to Staging"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy-production:
    name: 🎉 Deploy to Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        
      - name: 📂 Deploy to Production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PROD_FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          server-dir: /apps/${{ secrets.CLIENT_DOMAIN }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
            **/.env.*